Repository planetary-social/planetary-ios, pull requests merged in 2022-07, with the labels that each got.

#697 replace time ago in feed for messages with the poster's identity
  CHANGELOG.md
  Source/Controller/ThreadViewController.swift
  Source/UI/PostCellView.swift
  Source/UI/PostHeaderView.swift
  Source/UI/ThreadReplyView.swift
Labels: ui, small

#702 adding a bunch of indexes to speed up queries
  Source/GoBot/ViewDatabase.swift
Labels: enhancement, tech, small

#715 Only run the fix for preloaded pub messages once
  Frameworks/GoSSB.xcframework/Info.plist
  Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
  Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
  Source/Service/PreloadedPubService.swift
Labels: Skip-Changelog

#726 adding queer.family pub
  CHANGELOG.md
  Resources/Preload.bundle/Pubs/BlobIdentifiers.plist
  Resources/Preload.bundle/Pubs/Blobs/queer.png
  Resources/Preload.bundle/Pubs/preloadedPubs.json
  Source/Configs/Planetary.debug.xcconfig
  Source/Configs/Planetary.release.xcconfig
  Source/Service/PreloadedPubService.swift
Labels: enhancement, small

#735 Fix issue where app badge and notifications tab badge mismatch
  Planetary.xcodeproj/project.pbxproj
  Source/Bot/Bot.swift
  Source/Bot/Operations/ClearUnreadNotificationsOperation.swift
  Source/Controller/NotificationsViewController.swift
  Source/FakeBot/FakeBot.swift
  Source/GoBot/GoBot.swift
  Source/GoBot/ViewDatabase.swift
  Source/Localization/Text.swift
  Source/Localization/af-ZA.lproj/Generated.strings
  Source/Localization/ar-SA.lproj/Generated.strings
  Source/Localization/ca-ES.lproj/Generated.strings
  Source/Localization/cs-CZ.lproj/Generated.strings
  Source/Localization/da-DK.lproj/Generated.strings
  Source/Localization/de-DE.lproj/Generated.strings
  Source/Localization/el-GR.lproj/Generated.strings
  Source/Localization/en-US.lproj/Generated.strings
  Source/Localization/en.lproj/Generated.strings
  Source/Localization/es-AR.lproj/Generated.strings
  Source/Localization/es-ES.lproj/Generated.strings
  Source/Localization/es-UY.lproj/Generated.strings
  Source/Localization/es.lproj/Generated.strings
  Source/Localization/fi-FI.lproj/Generated.strings
  Source/Localization/fr-FR.lproj/Generated.strings
  Source/Localization/he-IL.lproj/Generated.strings
  Source/Localization/hu-HU.lproj/Generated.strings
  Source/Localization/it-IT.lproj/Generated.strings
  Source/Localization/ja-JP.lproj/Generated.strings
  Source/Localization/ko-KR.lproj/Generated.strings
  Source/Localization/mi-NZ.lproj/Generated.strings
  Source/Localization/nl-NL.lproj/Generated.strings
  Source/Localization/no-NO.lproj/Generated.strings
  Source/Localization/pl-PL.lproj/Generated.strings
  Source/Localization/pl.lproj/Generated.strings
  Source/Localization/pt-BR.lproj/Generated.strings
  Source/Localization/pt-PT.lproj/Generated.strings
  Source/Localization/ro-RO.lproj/Generated.strings
  Source/Localization/ru-RU.lproj/Generated.strings
  Source/Localization/sr-SP.lproj/Generated.strings
  Source/Localization/sv-SE.lproj/Generated.strings
  Source/Localization/tr-TR.lproj/Generated.strings
  Source/Localization/uk-UA.lproj/Generated.strings
  Source/Localization/vi-VN.lproj/Generated.strings
  Source/Localization/zh-CN.lproj/Generated.strings
  Source/Localization/zh-TW.lproj/Generated.strings
Labels: Skip-Changelog

#737 Add git lfs fsck CI job
  .github/workflows/main.yml
Labels: Skip-Changelog

#739 Optimize read notification queries
  Planetary.xcodeproj/project.pbxproj
  Source/App/AppDelegate+Push.swift
  Source/Bot/Operations/CountUnreadNotificationsOperation.swift
  Source/Controller/NotificationsViewController.swift
  Source/GoBot/GoBot.swift
  Source/GoBot/ViewDatabase.swift
  UnitTests/ReportTests.swift
Labels: Skip-Changelog

#747 Log app version on launch
  Source/App/AppDelegate.swift
Labels: Skip-Changelog

#764 New logic for applying the ban list
  Source/GoBot/GoBot.swift
  Source/GoBot/GoBotInternal.swift
  Source/GoBot/ViewDatabase.swift
  UnitTests/ViewDatabaseTests.swift
Labels: Skip-Changelog

#768 Add new test pub
  Source/Configs/Planetary.debug.xcconfig
  Source/Configs/Planetary.release.xcconfig
Labels: Skip-Changelog
